### ISSUE TITLE
Criar uma ordem sem itens 

### ISSUE THREAD

**Issue by camilohikage** [DeveloperCielo/LIO-SDK-API-Integracao-Remota-v1-PHP#2]
Como faço para criar uma ordem sem tem o item agregado ?

**Comment by frekele** [comment]
@camilohikage 
Não é permitido criar uma ordem sem itens.

Ao fazer o Post do Pedido você precisa adicionar pelo menos um item, logo após se estiver com status DRAFT você pode alterar, excluir e adicionar mais itens, mas sempre deve sobrar pelo menos um único item no total.
Após fazer o PLACE, não é possível mais alterar o pedido.

**Comment by frekele** [comment]
De nada pela ajuda.
