### ISSUE TITLE
O Método orderGetItem não retorna nada

### ISSUE THREAD

**Issue by camilohikage** [DeveloperCielo/LIO-SDK-API-Integracao-Remota-v1-PHP#5]
O Método orderGetItem não retorna nenhum resultado.

**Comment by frekele** [comment]
@camilohikage 
Provavelmente você não inclui nada ou não tem os códigos de autorização da Cielo para a comunicação.

Ou Talvez este componente esteja quebrada, eu sugiro que você implemente um componente em PHP, pois tanto essa sdk PHP a java e a C# foram gerados automaticamente pelo swagger-codegen, e basta uma olhada no codigo gerado para você ver a péssima qualidade dele.

Você pode dar uma olhada no meu componente java e se basear nele.
https://github.com/frekele/cielo-lio-remote-client

Qualquer duvida que tenha, a Cielo não irá te ajudar por aqui, você precisa criar uma conta e abrir um ticket com a duvida.
https://devcielo.zendesk.com/hc/en/requests/new

abraços

**Comment by camilohikage** [comment]
Obrigado !
